### PR TITLE
Removed references to smarttab

### PR DESCRIPTION
**Pull request by bound-variable**
- Improved English mechanics: fixed grammar and punctuation; improved diction.
- Improved English mechanics: fixed grammar and punctuation; improved diction.
- Removed references to smarttab (added by mistake last time)

**Breaking change**: yes/no

**Description**:

### CODE REVIEW

**Comment by andreyorst** [comment]
I think I have already removed that

**Comment by bound-variable** [comment]
I pulled the repo first and it said there weren't any changes.

**Comment by andreyorst** [comment]
Well, I've defenitively removed these references:

https://github.com/andreyorst/powerline.kak/commit/c5ef9a845bbd886c73ef00c0efff986e02d5f5d8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L44-L47

https://github.com/andreyorst/powerline.kak/commit/c5ef9a845bbd886c73ef00c0efff986e02d5f5d8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L183-L184

Perhaps you forgot to change branches when pulling?

**Comment by bound-variable** [comment]
> Perhaps you forgot to change branches when pulling?

Yes, I forgot to change branches.

**Pull request closed without merging**
