### PR TITLE
Improved English mechanics: fixed grammar and punctuation; improved diction.

### PR DESCRIPTION
**Pull request by Pound-Hash**
**Breaking change**: yes/no

**Description**:
I've edited the introduction to the README. While doing so, I made the introduction a single line composed of multiple sentences. The original introduction is broken up across multiple lines. I'm not sure what the reason for this is. If it's necessary, I can change it back to cross multiple lines.

If the changes are accepted, I can edit the entire README for you.

### CODE REVIEW

**Comment by andreyorst** [comment]
Thanks! But please keep one sentence per line, as it makes reviewing diffs a much simpler task.

https://rhodesmill.org/brandon/2012/one-sentence-per-line

**Comment by Pound-Hash** [comment]
Okay! I didn't know that. I'll read that article.

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by Pound-Hash** [comment]
I'm new to working with git like this. Let me know if everything is okay.

**Comment by andreyorst** [comment]
Looks great to me, but It seems that there are some conflicts for some reason. I don't think I've pushed anything, though.

**Comment by Pound-Hash** [comment]
> Looks great to me, but It seems that there are some conflicts for some reason. I don't think I've pushed anything, though.

On my end, I GitHub is saying there are no conflicts. Is there anything I can do?

**Comment by andreyorst** [comment]
I wasn't able to rebase for some reason, so I've just merged it. Thanks! I'll give it a few tweaks here and there, as Ive spotted some mistakes of my own.

**Pull request merged**
